name = "SUNRepresentations"
uuid = "1a50b95c-7aac-476d-a9ce-2bfc675fc617"
authors = ["Maarten Van Damme <Maarten.VanDamme@UGent.be> and Jutho Haegeman <jutho.haegeman@ugent.be>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RationalRoots = "308eb6b3-cc68-5ff3-9e97-c3c4da4fa681"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
